dataset:
  name: multiviewx

detection:
  name: mvdetr

tracking:
  name: deep_sort_bev
  params:
    tracking_strategy: two_stage_visibility
    max_age: 10
    app_dist_thresh: 0.2
    motion_dist_thresh: 40.0
    gating_dist: 40.0
    visibility_switching_thresh: 200.0

