dataset:
  name: wildtrack

detection:
  name: mvdetr

tracking:
  name: deep_sort_bev
  params:
    max_age: 4
    dist_thresh: 0.4
    gating_dist: 40.0
    use_weighted_embedding: false
    use_visibility_switching: true
    visibility_switching_thresh: 200.0

