dataset:
  name: wildtrack

detection:
  name: mvdetr

tracking:
  name: deep_sort_bev
  params:
    tracking_strategy: visibility_switching
    max_age: 4
    dist_thresh: 0.4
    gating_dist: 40.0
    visibility_switching_thresh: 200.0

